# -*- coding: utf-8 -*-
"""Data Import

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Z2acM-Gkmbk2zk5Ef5l8Xy5fBAFK5ms
"""

import csv
import pandas as pd

heart_csv = pd.read_csv('heart.csv')
o2_csv = pd.read_csv('o2Saturation.csv')
placement_csv = pd.read_csv('Placement_Data_Full_Class.csv')
weather_csv = pd.read_csv('weatherAUS_parsed.csv')
house_csv = pd.read_csv('housePrices.csv')

X = heart_csv.drop(columns=['target'])
y = heart_csv['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X = house_csv.drop(columns=['Beds','Zip'])
y = house_csv['Beds']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X = weather_csv.drop(columns=['Location','MinTemp','MaxTemp','Rainfall','WindGustDir','WindGustSpeed','WindDir9am','WindDir3pm','WindSpeed9am','WindSpeed3pm','Humidity9am','Humidity3pm','Pressure9am','Pressure3pm','Cloud9am','Cloud3pm','Temp9am','Temp3pm','RainToday','RainTomorrow'])
y = weather_csv['Binary RainTomorrow']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X = placement_csv.drop(columns=['salary','gender','ssc_b','hsc_b','hsc_s','degree_t','workex','specialisation','status'])
y = placement_csv['status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)