# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ymHFA_iKV3mSrA9l7OyLmAnelJ5bLuIO
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from dataset import *

import csv
import pandas as pd

def training_logistic_regression(X,y):

  lrc = LogisticRegression(randomstate=0)
  lrc.fit(X,y)

  return lrc

campus = CampusDataset()
heart = HeartDataset()
housing = HousingDataset()
rain = RainDataset()

[X, Y] = campus.get(['binary status'],['ssc_p','hsc_p','degree_p','etest_p','mba_p','salary','binary specialisation','binary workex','numerical degree_t','binary gender','binary ssc_b','binary hsc_b','numerical hsc_s'])

[X, Y] = heart.get(['target'],['chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal'])

[X, Y] = housing.get(['Beds'],['Living_Space_sq_ft','Baths','Zip','Year','SalePrice'])

[X, Y] = rain.get(['RainTomorrow'],['WindGustDir','WindGustSpeed','WindSpeed9am','WindSpeed3pm','Humidity9am','Humidity3pm'],ommit_nan=True)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

classifier = LogisticRegression(random_state=0).fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))